---
id: rubyhiroba-2014
base_name: travis-yml-tips
tags:
  - rabbit
presentation_date: 2014/09/21
version: 2014.9.21.0
licenses:
  - CC BY 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
